# Generated by Django 5.1.5 on 2026-08-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldassets', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='overduenotice',
            constraint=models.UniqueConstraint(fields=('checkout', 'notice_date'), name='uniq_notice_per_checkout_per_day'),
        ),
    ]
